development: &default
  adapter: postgresql
  encoding: unicode
  username: db
  password: db
  port: 15432
  host: localhost
  database: wheeler_centre_development

test:
  <<: *default
  database: wheeler_centre_test
  min_messages: warning

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
