development: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  database: wheeler_centre_development

test:
  <<: *default
  database: wheeler_centre_test
  min_messages: warning

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
